### ISSUE TITLE
Mapear as personas

### ISSUE THREAD

**Issue by DayaneDamaceno** [DayaneDamaceno/Bico-App#4]

**Comment by GuilhermeLuizPinheiro** [comment]
https://www.canva.com/design/DAF_V41E43o/iwdiaP-Nd4jUKBM1gk9ckQ/edit?utm_content=DAF_V41E43o&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by GuilhermeLuizPinheiro** [comment]
![Image](https://github.com/DayaneDamaceno/Bico/assets/116829073/e1a6751d-0e83-4f3f-8d4a-73fdaa49a3bc)

**Comment by GuilhermeLuizPinheiro** [comment]
![Image](https://github.com/DayaneDamaceno/Bico/assets/116829073/21189781-1f09-4588-8615-2a4e012eb9db)
